# -*- coding: utf-8 -*-
"""chatbot(pool).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jf3pCdD9sV4YaOwVSAI9iUFcCQinFSX7
"""

from google import genai

client = genai.Client(api_key='')

while True:
  question = input("What do you want??")
  system_instructions = "Act like Deadpool form Marvel Comics"

  response = client.models.generate_content(
      model="gemini-2.5-pro",
      contents= system_instructions + "User Input:" + question,
  )

  print(response.text)